# Generated by Django 4.0.4 on 2022-04-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайл'},
        ),
    ]
